### ISSUE TITLE
On new installation, odd placement of 'View All Items'

### ISSUE THREAD

**Issue by patrickmj** [omeka/theme-thanksroy#24]
New installation, 2 items. Both FF and Chromium, 'View All Items' is oddly placed in Recently Added area.

![royrecentlyadded](https://cloud.githubusercontent.com/assets/153262/11666931/eb149240-9dbc-11e5-961e-e3f0d737935d.png)

**Comment by zerocrates** [comment]
I suspect this is happening because you don't have a description for that item? Or something like that... something's not clearing. The whole item container and/or the view all items link should be doing so at any rate, regardless of the presence or absence of a description.

**Comment by patrickmj** [comment]
Sorta. Added a description, same thing. With a longer description, it looks better, but still wonky
