### ISSUE TITLE
Testing: "Narrow by" inputs appear inline and "view all items" link clears properly

### ISSUE THREAD

**Issue by kimisgold** [omeka/theme-thanksroy#26]
Issue #24: On advanced item search, the "narrow by" fields should appear on a single line in all browsers.

Issue #25: On the homepage, if recent items have a short or no description, the "view all items" link should clear to a new line.

**Comment by mebrett** [comment]
Narrow by fields appear on a single line on Chrome, Safari, and Firefox.

View All Items cleared to a new line when recent items had no description at all, when the description was very short, and when the description was quite long.
