### ISSUE TITLE
Clicking on parent item in mobile menu does not collapse submenu or go to parent page

### ISSUE THREAD

**Issue by kimisgold** [omeka/theme-thanksroy#27]
Menus at mobile widths work fine on desktop, but break on mobile touch devices.

**Comment by kimisgold** [comment]
A solution on the 'sub-nav-toggle-button' branch is ready for testing.

* Parent link of a child menu is clickable and navigates to its respective page on both touch and non-touch devices 
* Toggle icon expands and collapses on touch devices.

@mebrett

**Comment by mebrett** [comment]
Success on both counts. Toggle expands and collapses, parent pages open just fine.
