### ISSUE TITLE
Neatline | Browse Exhibits first list item indent

### ISSUE THREAD

**Issue by jim1001** [omeka/theme-thanksroy#34]
The first item on my Neatline | Browse Exhibits page appears indented to the middle of the screen. Happens with theme "Thanks Roy" (current v2.5.1). Doesn't happen with themes The Daily or Big Stuff. Happens with Neatline v2.6.3 & 2.6.1. Not sure if it is Theme or plugin problem so have posted to both.
![Neatline_indent](https://user-images.githubusercontent.com/16447481/69234910-2e643b80-0b88-11ea-8753-6032dc4fe3af.JPG)

Any suggestions how to fix? 

(update: after changing the second exhibit this also was indented same amount as first on above page)

Thanks

**Comment by zerocrates** [comment]
Can you share a link to this page? It's always easier when we can see the problem and the styles "live."

This looks to me like it's just a problem with "floating": the first exhibit title there is getting pushed over by, it looks like, the "Neatline | Browse Exhibits" header. So the solution probably involves either removing some `float: left` styles or adding a `clear` style.

**Comment by jim1001** [comment]
Thanks for reply.

[Here's the link](https://minerva.manchester.ac.uk/demo-b/neatline)

**Comment by jim1001** [comment]
I've just seen a reply to same issue i raised on the Neatline GitHub page. Here's what was said:

> Thanks for bringing this to our attention. We'll be making some changes to the Neatline Browse Exhibits page in the future to fix this issue, but in the mean time, if you'd like to fix this on your end, enter the following css into your theme's style.css file:
> #primary h2 .neatline {
>   display:block;
>   clear:both;
> }
> You can find the style.css file in the css folder within your theme folder. This should resolve the issue, but please follow up if not.
