### ISSUE TITLE
Any chance of an Omeka S version?

### ISSUE THREAD

**Issue by christiancasey** [omeka/theme-thanksroy#35]
I'm working on a new site in Omeka S that parallels an existing site in Omeka. We used Thanks, Roy in the older site, and I would like to duplicate that design in the new one. Is there any chance that you will be creating a new version of this theme for Omeka S?

**Comment by kimisgold** [comment]
We're in the process of planning more themes for Omeka S, and creating successors to existing Omeka Classic themes has been one of the suggestions. So yes, there may be a Thanks, Roy for Omeka S, but it's still at the earliest stages of development.

**Comment by christiancasey** [comment]
Great news! Thank you for your work and for this quick response.

**Comment by kimisgold** [comment]
We've released an Omeka S port of the theme here: https://omeka.org/s/themes/thanksroy/ Thanks for your patience!
