### ISSUE TITLE
Test improved color settings for mobile

### ISSUE THREAD

**Issue by kimisgold** [omeka/theme-thanksroy#49]
On the `master` branch, test the following: 

* Setting button background and text colors applies to mobile navigation styles. The mobile navigation was previously set up to borrow from different color values that produced more illegible combinations. The change was made in the hopes that values that work for buttons should be similarly appropriate for the mobile navigation interface elements.

This should be tested on major browsers for both desktop and mobile devices.

**Comment by katknow** [comment]
It seems to work for me across browsers and on Apple mobile devices. Tested on Edge, Safari, Chrome, and Firefox.
